# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='myrestaurants'),
        ),
    ]
