# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-12 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurants', '0002_dish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
    ]
