name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Set up Chromedriver for e2e
      uses: nanasess/setup-chromedriver@v2
    - name: Install Dependencies
      run: |
        pip install pipenv
        pipenv install --dev
    - name: Run Tests
      run: |
        pipenv run python manage.py test
        pipenv run python manage.py collectstatic --noinput
        pipenv run python manage.py behave